language: python
sudo: false
cache: pip
matrix:
  include:
    - python: '3.9'
      env:
        - TOXENV=py39
    - python: '3.10'
      env:
        - TOXENV=py310
    - python: '3.11'
      env:
        - TOXENV=py311
    - python: '3.12'
      env:
        - TOXENV=py312
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - pip3 --version
  - pip3 install flask tox flake8 bandit sphinx pallets_sphinx_themes
  - pip3 freeze
script:
  - make all
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
